services:
  - type: web
    name: million-dollar-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python dashboard.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    autoDeploy: true
